/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconName, } from "@fortawesome/fontawesome-common-types";
export namespace Components {
    interface FaIcon {
        /**
          * The name of the icon.
         */
        "name": IconName;
        /**
          * The size of the icon.
         */
        "size"?: "x-small" | "small" | "medium" | "large" | "x-large" | "xx-large";
        /**
          * The icon prefix.
         */
        "type": "fas" | "far" | "fab";
    }
}
declare global {
    interface HTMLFaIconElement extends Components.FaIcon, HTMLStencilElement {
    }
    var HTMLFaIconElement: {
        prototype: HTMLFaIconElement;
        new (): HTMLFaIconElement;
    };
    interface HTMLElementTagNameMap {
        "fa-icon": HTMLFaIconElement;
    }
}
declare namespace LocalJSX {
    interface FaIcon {
        /**
          * The name of the icon.
         */
        "name"?: IconName;
        /**
          * The size of the icon.
         */
        "size"?: "x-small" | "small" | "medium" | "large" | "x-large" | "xx-large";
        /**
          * The icon prefix.
         */
        "type"?: "fas" | "far" | "fab";
    }
    interface IntrinsicElements {
        "fa-icon": FaIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fa-icon": LocalJSX.FaIcon & JSXBase.HTMLAttributes<HTMLFaIconElement>;
        }
    }
}
